iot_devices_repo_url: "https://github.com/AlexandreN8/iot-edge-platform.git"
iot_devices_repo_dest: "/home/{{ ansible_user | default(lookup('env', 'USER')) }}/iot-edge-platform"
iot_devices_image_name: iot_devices:local
iot_devices_container_name: iot_devices
iot_devices_network_name: iot_network
iot_devices_build_context: "{{ iot_devices_repo_dest }}/edge/iot_devices"
