[SERVICE]
    Flush        5
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name         forward
    Listen       0.0.0.0
    Port         24224

[FILTER]
    Name         parser
    Match        *
    Key_Name     log
    Parser       json_log
    Reserve_Data On

[OUTPUT]
    Name         stdout
    Match        *
    Format       json_lines

[OUTPUT]
    Name         loki
    Match        *
    Host         loki
    Port         3100
    Labels       job=paas
    Label_Keys   $service,$category,$level