FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir --only-binary=:all: -r requirements.txt

COPY main.py .
COPY buffer.py .
COPY filtering.py .
COPY schema_validation.py .
COPY sender.py .
COPY heartbeat.py .

HEALTHCHECK --interval=10s --timeout=3s --retries=3 --start-period=15s \
  CMD find /app/heartbeat_mqtt -mmin -1 && find /app/heartbeat_sender -mmin -1 || exit 1

RUN useradd --create-home --shell /bin/bash appuser \
    && chown -R appuser:appuser /app
USER appuser

CMD ["python", "main.py"]