repo_url: "https://github.com/AlexandreN8/iot-edge-platform.git"
repo_dest: "/home/{{ ansible_user }}/iot-edge-platform"
image_name: edge_processor:local
container_name: edge_processor
network_name: iot_network
build_context: "{{ repo_dest }}/edge/edge_processor"
