edge_processor_repo_url: "https://github.com/AlexandreN8/iot-edge-platform.git"
edge_processor_repo_dest: "/home/{{ ansible_user | default(lookup('env', 'USER')) }}/iot-edge-platform"
edge_processor_image_name: edge_processor:local
edge_processor_container_name: edge_processor
edge_processor_network_name: iot_network
edge_processor_build_context: "{{ edge_processor_repo_dest }}/edge/edge_processor"
