repo_url: "https://github.com/AlexandreN8/iot-edge-platform.git"
repo_dest: "/home/{{ ansible_user | default(lookup('env','USER')) }}/iot-edge-platform"
image_name: cleaner:local
container_name: cleaner
network_name: paas_network
build_context: "{{ repo_dest }}/paas/services/cleaner"
