apiVersion: 1

datasources:
  - name: IoT Postgres
    type: postgres
    uid: postgres-iot
    access: proxy
    url: postgres:5432
    user: iot
    isDefault: true
    editable: false
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: iot
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false